In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import GPy
from IPython.display import display
GPy.plotting.change_plotting_library('matplotlib')
import GP_functions1 as GP

In [2]:
position=np.array([[   0.   ,  0.        ],[ 794.36576595 ,  43.85822902], [ 449.31175435,  178.73675336], [2031.48005906 ,  71.47280391]])
tu = GP.TurbineUtility()

In [3]:
name = "all_dataset.csv"
gp_model = GP.GP_train().train_model() # trains model on "all_dataset.csv"


 C:\Users\jingj\Documents\GitHub\cfd_gp\GP_functions1.py:60: FutureWarning:The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.


In [4]:
# CREATE PREDICTING CLASS from which attenuation predictions are made
gp = GP.GP_predict(gp_model) # create predicting class


In [7]:
#make predictions
position=np.array([[   0.   ,  0.        ],[ 794.36576595 ,  43.85822902], [ 449.31175435,  178.73675336], [2031.48005906 ,  71.47280391]])
tu = GP.TurbineUtility()
neigh=tu.nlist(position,4)
print(neigh)
fingerprint=tu.fingerprint(position,4)
print(fingerprint)
[refwind,referr]=gp_model.predict(fingerprint)
refwind2=gp.predict(position,4)
print(refwind,referr,refwind2)

[[], [0], [], [0, 1, 2]]
[[1.         0.34493215 1.04700824]
 [0.57034779 0.14494835 1.04700824]
 [1.         0.34493215 1.04700824]
 [0.52706604 0.04468339 0.0772671 ]]
[[7.39822176]
 [6.20027228]
 [7.39822176]
 [4.99785094]] [[0.00659174]
 [0.00694498]
 [0.00659174]
 [1.24979843]] [[7.39822176]
 [6.20027228]
 [7.39822176]
 [4.99785094]]


In [ ]:
slices = [0.2, 0.5, 0.8, 1.0]
figure = GPy.plotting.plotting_library().figure(4, 1)
                            
for i, y in zip(range(4), slices):
    canvas = m.plot(figure=figure, fixed_inputs=[(1,y)], row=(i+1), plot_data=False)
#GPy.plotting.show(canvas, filename='basic_gp_regression_notebook_slicing')

In [ ]:
[Ypred,Yvar]=m.predict(Xtest)
error_test=np.abs(Ypred-Ytest)
np.max(error_test)

In [ ]:
[Yval,Yvalvar]=m.predict(Xtrain)
error_train=np.abs(Yval-Ytrain)
np.max(error_train)

In [ ]:
[Yall,Yallvar]=m.predict(X)
error_all=np.abs(Yall-Y)
np.max(error_all)

In [ ]:
#make predictions
position=np.array([[   0.   ,  0.        ],[ 794.36576595 ,  43.85822902], [ 449.31175435,  178.73675336], [2031.48005906 ,  71.47280391]])
neigh=gp.nlist(position,4)
#fingerprints=np.array(gp.finfinpr.calculate(turb*4,position,neigh,symbol))
refwind=gp.predict(position,4)
print(neigh)
print(refwind)


In [ ]:
a = plt.axes(aspect='equal')
plt.scatter(Ytest, Ypred,c=Xtest[:,0])     #"Fingerprint(G2)"
plt.scatter(Ytrain, Yval,c=Xtrain[:,0])  #"Fingerprint(G2)"
plt.xlabel('True Values [Ref_wind_speed]')
plt.ylabel('Predictions [Ref_wind_speed]')
cbar=plt.colorbar()
cbar.set_label('Fingerprint(G2)')
lims = [4.5, 8]
plt.xlim(lims)
plt.ylim(lims)
_ = plt.plot(lims, lims)

In [ ]:
a = plt.axes(aspect='equal')
plt.scatter(Ytest, Ypred,c=Xtest[:,1])     #"Fingerprint(G4)"
plt.scatter(Ytrain, Yval,c=Xtrain[:,1])  #"Fingerprint(G4)"
plt.xlabel('True Values [Ref_wind_speed]')
plt.ylabel('Predictions [Ref_wind_speed]')
cbar=plt.colorbar()
cbar.set_label('Fingerprint(G4)')
lims = [4.5, 8]
plt.xlim(lims)
plt.ylim(lims)
_ = plt.plot(lims, lims)

In [ ]:
a = plt.axes(aspect='equal')
plt.scatter(Ytest, Ypred,c=Xtest[:,2])     #"Fingerprint(G6)"
plt.scatter(Ytrain, Yval,c=Xtrain[:,2])  #"Fingerprint(G6)"
plt.xlabel('True Values [Ref_wind_speed]')
plt.ylabel('Predictions [Ref_wind_speed]')
cbar=plt.colorbar()
cbar.set_label('Fingerprint(G6)')
lims = [4.5, 8]
plt.xlim(lims)
plt.ylim(lims)
_ = plt.plot(lims, lims)

In [ ]:
plt.scatter(dataset_pos[:,0], dataset_pos[:,1],c=error_all)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Error Rate Locations')
cbar=plt.colorbar()
cbar.set_label('Absolute Error Rate (m/s)')

In [ ]:
a = plt.axes
plt.scatter(Xtest[:,0], Xtest[:,1],c=np.abs(Ypred))
plt.scatter(Xtrain[:,0], Xtrain[:,1],c=np.abs(Yval))
#plt.scatter(train_labels, train_predictions)
plt.xlabel('Fingerprint(G2)')
plt.ylabel('Fingerprint(G4)')
plt.title('Predicted Values')
cbar=plt.colorbar()
cbar.set_label('Predicted Wind Speed (m/s)')

In [ ]:
a = plt.axes
plt.scatter(Xtest[:,0], Xtest[:,1],c=np.abs(Ytest))
plt.scatter(Xtrain[:,0], Xtrain[:,1],c=np.abs(Ytrain))
#plt.scatter(train_labels, train_predictions)
plt.xlabel('Fingerprint(G2)')
plt.ylabel('Fingerprint(G4)')
plt.title('Actual CFD Values')
cbar=plt.colorbar()
cbar.set_label('Predicted Wind Speed (m/s)')

In [ ]:
a = plt.axes
plt.scatter(X[:,0], X[:,1],c=error_all)
#plt.scatter(Xtrain[:,0], Xtrain[:,1],c=np.abs(Ytrain))
#plt.scatter(train_labels, train_predictions)
plt.xlabel('Fingerprint(G2)')
plt.ylabel('Fingerprint(G4)')
plt.title('Error Rate (m/s)')
cbar=plt.colorbar()
cbar.set_label('Absolute Error Rate (m/s)')

In [ ]:
plt.hist(error_all, bins=10)
plt.xlabel('Prediction Error [Ref_wind_speed]')
plt.title('error_all')
_ = plt.ylabel('Count')

In [ ]:
plt.hist(error_test, bins=10)
plt.xlabel('Prediction Error [Ref_wind_speed]')
plt.title('error_test')
_ = plt.ylabel('Count')

In [ ]:
import numpy
from mayavi.mlab import *

def test_points3d():


    x = X[:,0] #Fingerprint(G2)
    y = X[:,1] #Fingerprint(G4)
    z = X[:,2] #Fingerprint(G6)
    s = error_all.flatten()
    colorbar(orientation='vertical')
    xlabel('Fingerprint(G2)')
    ylabel('Fingerprint(G4)')
    zlabel('Fingerprint(G6)')
    return points3d(x, y, z, s, colormap="blue-red", scale_factor=0.1)
test_points3d()
#colorbar(object=all_labels, title="Points in Mayavi")
#view()
show()